spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger
    username: messenger
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    rest:
      base-path: /api